DaniAm94/proj-html-vuejs

src/components/AppFooter/AppFooter.vue, src/components/AppFooter/FooterForm.vue, src/components/AppFooter/FooterInfo.vue, src/components/AppFooter/FooterNav.vue
=> 2 app footer

src/assets/data/index.js
=> filled index.js file

src/components/BaseButton.vue, src/components/CarouselButton.vue
=> change icon name

src/components/AppMain/Sections/EventsSection.vue
=> added event section blocks

src/components/AppMain/Sections/ProfessionalSection.vue
add section professional blocks
=> add section professional

src/components/AppMain/Sections/ExpertTrainersSection.vue
=> add expert trainers structure

src/components/AppMain/Sections/ArticlesSection.vue
=> add articles section

src/components/AppMain/Sections/SpecialPacksSection.vue
add structure special packs section
=> 22 section special packs

src/components/AppMain/Sections/CardsList.vue
=> add card list

src/components/AppFooter/AppFooter.vue, src/components/AppFooter/FooterForm.vue, src/components/AppFooter/FooterInfo.vue, src/components/AppFooter/FooterNav.vue
=> finisced footer style

src/components/AppMain/Sections/SectionCard.vue
=> completed card component

package-lock.json, package.json, src/App.vue, src/assets/scss/style.scss, src/components/AppMain/MainJumbotron.vue
add jumbotron content, add font
=> jumbotron content

src/components/AppMain/Sections/SectionCard.vue, src/components/AppMain/Sections/SpecialPacksSection.vue
=> add special packs content

src/assets/data/index.js, src/components/AppMain/Sections/ArticlesSection.vue
=> add card articles section

src/components/AppFooter/FooterNav.vue
=> fixed footer links

src/components/AppHeader/AppHeader.vue, src/components/AppHeader/HeaderNav.vue
=> add other content header

src/App.vue
=> modified scrollbar

src/components/AppMain/MainJumbotron.vue
add autoplay to jumbotron with setInterval
=> autoplay jumbotron

src/components/AppMain/MainJumbotron.vue
=> fixed autoplay

src/assets/data/index.js
fixed jumbotrondata in  index.js
=> fixed index.js

src/components/AppHeader/HeaderNav.vue
=> add dropdown menu header

src/components/AppMain/MainJumbotron.vue
=> comments - mainjumbotron
